/**
 * reportService.js
 * ─────────────────────────────────────────────────────────────
 * Pure jsPDF PDF generation — no html2canvas, no DOM capture.
 * Uses ONLY standard Latin-1 characters so Helvetica renders
 * correctly. No emojis anywhere in doc.text() calls.
 */
import jsPDF from 'jspdf';

/* ── Palette ─────────────────────────────────────────────────── */
const C = {
  green:      '#059669',
  greenMid:   '#10b981',
  greenLight: '#d1fae5',
  greenBg:    '#f0fdf4',
  blue:       '#3b82f6',
  amber:      '#f59e0b',
  red:        '#ef4444',
  purple:     '#8b5cf6',
  slate900:   '#0f172a',
  slate700:   '#334155',
  slate500:   '#64748b',
  slate400:   '#94a3b8',
  slate300:   '#cbd5e1',
  slate200:   '#e2e8f0',
  slate100:   '#f1f5f9',
  white:      '#ffffff',
};

/* Category config — ASCII labels only, no emoji */
const CAT_META = {
  transport:   { label: 'Transport',   color: C.blue   },
  electricity: { label: 'Electricity', color: C.amber  },
  food:        { label: 'Food',        color: C.green  },
  shopping:    { label: 'Shopping',    color: C.purple },
  energy:      { label: 'Energy',      color: C.red    },
  other:       { label: 'Other',       color: C.slate400 },
};

/* ── Helpers ─────────────────────────────────────────────────── */
function fmtKg(kg) {
  if (kg == null || isNaN(kg)) return '--';
  if (kg >= 1000) return `${(kg / 1000).toFixed(2)} t CO2e`;
  if (kg >= 1)    return `${kg.toFixed(2)} kg CO2e`;
  return `${(kg * 1000).toFixed(0)} g CO2e`;
}

function ecoRating(score) {
  if (score >= 751) return { label: 'Excellent',    tier: 'A', color: C.green   };
  if (score >= 671) return { label: 'Good',          tier: 'B', color: C.greenMid };
  if (score >= 551) return { label: 'Fair',           tier: 'C', color: C.amber  };
  return               { label: 'Needs Action', tier: 'D', color: C.red    };
}

function cap(s) {
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : '';
}

/* ── Layout helpers ──────────────────────────────────────────── */
function pageHeader(doc, W) {
  doc.setFillColor(C.green);
  doc.rect(0, 0, W, 10, 'F');
  doc.setFontSize(6.5);
  doc.setTextColor(C.white);
  doc.text('CarbonTrack  -  Sustainability Report', 10, 6.5);
}

function pageFooter(doc, W, H, n, total) {
  doc.setFillColor(C.slate200);
  doc.rect(0, H - 9, W, 9, 'F');
  doc.setFontSize(6.5);
  doc.setTextColor(C.slate500);
  doc.text(
    `Generated by CarbonTrack  -  ${new Date().toLocaleDateString()}`,
    10, H - 3,
  );
  doc.text(`Page ${n} of ${total}`, W - 10, H - 3, { align: 'right' });
}

function rr(doc, x, y, w, h, r, color, style = 'F') {
  doc.setFillColor(color);
  doc.roundedRect(x, y, w, h, r, r, style);
}

function sectionTitle(doc, text, x, y, sub = '') {
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.slate900);
  doc.text(text, x, y);
  if (sub) {
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate500);
    doc.text(sub, x, y + 6);
    return y + 11;
  }
  return y + 7;
}

function hLine(doc, x, y, w) {
  doc.setDrawColor(C.slate200);
  doc.setLineWidth(0.3);
  doc.line(x, y, x + w, y);
}

/* ── Category bar chart ──────────────────────────────────────── */
function drawCategoryBars(doc, catData, x, startY, w) {
  const total    = catData.reduce((s, c) => s + c.value, 0);
  const BAR_H    = 9;
  const GAP      = 5;
  const LABEL_W  = 42;
  const VALUE_W  = 40;
  const BAR_AREA = w - LABEL_W - VALUE_W - 4;
  let y = startY;

  if (catData.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(C.slate400);
    doc.text('No category data for this period.', x, y + 8);
    return y + 20;
  }

  catData.forEach((cat) => {
    const pct  = total > 0 ? cat.value / total : 0;
    const barW = Math.max(0, pct * BAR_AREA);
    const meta = CAT_META[cat.category] ?? CAT_META.other;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate700);
    doc.text(meta.label, x, y + BAR_H - 1);

    // track
    rr(doc, x + LABEL_W, y, BAR_AREA, BAR_H, 1.5, C.slate100);
    // fill
    if (barW > 1) rr(doc, x + LABEL_W, y, barW, BAR_H, 1.5, meta.color);

    // value + pct
    doc.setFontSize(7.5);
    doc.setTextColor(C.slate500);
    doc.text(
      `${fmtKg(cat.value)}  (${(pct * 100).toFixed(0)}%)`,
      x + LABEL_W + BAR_AREA + 3,
      y + BAR_H - 1,
    );

    y += BAR_H + GAP;
  });

  return y;
}

/* ── 7-day sparkline bars ────────────────────────────────────── */
function drawWeeklyBars(doc, weeklyData, x, startY, w, h) {
  if (!weeklyData || weeklyData.length === 0) {
    doc.setFontSize(9);
    doc.setTextColor(C.slate400);
    doc.text('No weekly data available.', x + w / 2, startY + h / 2, { align: 'center' });
    return;
  }
  const keys    = ['transport', 'electricity', 'food', 'shopping', 'energy', 'other'];
  const totals  = weeklyData.map((d) => keys.reduce((s, k) => s + (d[k] ?? 0), 0));
  const maxVal  = Math.max(...totals, 0.01);
  const barW    = (w - 4) / weeklyData.length;

  weeklyData.forEach((d, i) => {
    const total = totals[i];
    const barH  = Math.max(1, (total / maxVal) * (h - 14));
    const bx    = x + 2 + i * barW;
    const by    = startY + (h - 14) - barH;

    rr(doc, bx, by, barW - 2, barH, 1, total > 0 ? C.green : C.slate200);

    doc.setFontSize(6.5);
    doc.setTextColor(C.slate500);
    doc.setFont('helvetica', 'normal');
    doc.text(d.day ?? `D${i + 1}`, bx + (barW - 2) / 2, startY + h - 3, { align: 'center' });
  });
}

/* ═══════════════════════════════════════════════════════════════
   Main export
   ═══════════════════════════════════════════════════════════════ */
export async function generateMonthlyReport({
  username,
  period,
  ecoScore,
  totalNow,
  topCat,
  avgPerEntry,
  entries,
  catData,
  topActivities,
  weeklyTrendData = [],
}) {
  const doc   = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W     = doc.internal.pageSize.getWidth();
  const H     = doc.internal.pageSize.getHeight();
  const M     = 14;
  const CW    = W - M * 2;
  const now   = new Date();
  const monthLabel = now.toLocaleString('default', { month: 'long', year: 'numeric' });
  const rating     = ecoRating(ecoScore ?? 500);
  const PAGES      = 5;

  /* ═══════════════════════════════════════
     PAGE 1 — COVER
     ═══════════════════════════════════════ */
  // Background
  rr(doc, 0, 0, W, H, 0, C.greenBg);

  // Hero band
  rr(doc, 0, 0, W, 62, 0, C.green);

  // White card on band
  rr(doc, M, 13, CW, 44, 4, C.white);

  // Brand name
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.green);
  doc.text('CarbonTrack', W / 2, 30, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(C.slate700);
  doc.text('Personal Sustainability Report', W / 2, 39, { align: 'center' });

  doc.setFontSize(9);
  doc.setTextColor(C.slate500);
  doc.text(`${monthLabel}  -  ${username}`, W / 2, 48, { align: 'center' });

  // Eco score circle
  const cx = W / 2, cy = 98;
  // Outer ring
  rr(doc, cx - 34, cy - 34, 68, 68, 34, C.greenLight);
  // Inner circle
  rr(doc, cx - 27, cy - 27, 54, 54, 27, rating.color);

  // Score number
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.white);
  doc.text(String(ecoScore ?? '--'), cx, cy + 4, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('/ 850', cx, cy + 11, { align: 'center' });

  doc.setFontSize(10.5);
  doc.setFont('helvetica', 'bold');
  doc.text(rating.label, cx, cy + 20, { align: 'center' });

  // "Eco Score" label above circle
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(C.slate500);
  doc.text('Eco Score', cx, cy - 37, { align: 'center' });

  // Quick stats
  const STRIP_Y = 142;
  const COL_W   = CW / 3;
  const stats   = [
    { label: 'Total CO2e',  value: fmtKg(totalNow) },
    { label: 'Activities', value: String(entries)  },
    { label: 'Top Source', value: topCat ? CAT_META[topCat.category]?.label ?? topCat.name : '--' },
  ];
  stats.forEach((s, i) => {
    const sx = M + i * COL_W;
    rr(doc, sx, STRIP_Y, COL_W - 3, 24, 3, C.white);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate500);
    doc.text(s.label, sx + (COL_W - 3) / 2, STRIP_Y + 8, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(C.slate900);
    doc.text(s.value, sx + (COL_W - 3) / 2, STRIP_Y + 17, { align: 'center' });
    doc.setFont('helvetica', 'normal');
  });

  // Period pill
  rr(doc, M, STRIP_Y + 30, 44, 9, 2.5, C.green);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.white);
  doc.text(`Period: ${cap(period)}`, M + 22, STRIP_Y + 36, { align: 'center' });

  pageFooter(doc, W, H, 1, PAGES);

  /* ═══════════════════════════════════════
     PAGE 2 — KPI SUMMARY
     ═══════════════════════════════════════ */
  doc.addPage();
  pageHeader(doc, W);
  pageFooter(doc, W, H, 2, PAGES);

  let y = 18;
  y = sectionTitle(doc, 'Summary Overview', M, y, `Key metrics for the ${period} period`);
  y += 3;

  // 4 KPI cards (2x2 grid)
  const kpiItems = [
    { label: 'Total Emissions',     value: fmtKg(totalNow),    color: '#dcfce7', accent: C.green   },
    { label: 'Avg per Activity',    value: fmtKg(avgPerEntry),  color: '#fef9c3', accent: C.amber   },
    { label: 'Activities Logged',   value: String(entries),    color: '#ede9fe', accent: C.purple  },
    { label: 'Top Emission Source', value: topCat ? (CAT_META[topCat.category]?.label ?? topCat.name) : 'None',
      color: '#fee2e2', accent: C.red },
  ];

  const CARD_W = CW / 2 - 3;
  const CARD_H = 30;
  kpiItems.forEach((item, i) => {
    const cx2 = M + (i % 2) * (CARD_W + 6);
    const cy2 = y + Math.floor(i / 2) * (CARD_H + 5);

    // Card background
    rr(doc, cx2, cy2, CARD_W, CARD_H, 3, item.color);
    // Left accent bar
    rr(doc, cx2, cy2, 4, CARD_H, 3, item.accent);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate500);
    doc.text(item.label, cx2 + 10, cy2 + 10);

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(C.slate900);
    doc.text(item.value, cx2 + 10, cy2 + 22);
    doc.setFont('helvetica', 'normal');
  });

  y += 2 * (CARD_H + 5) + 10;
  hLine(doc, M, y, CW);
  y += 9;

  // Category breakdown bars
  y = sectionTitle(doc, 'Emissions by Category', M, y, 'Breakdown for this period');
  y += 2;
  drawCategoryBars(doc, catData, M, y, CW);

  /* ═══════════════════════════════════════
     PAGE 3 — CHARTS
     ═══════════════════════════════════════ */
  doc.addPage();
  pageHeader(doc, W);
  pageFooter(doc, W, H, 3, PAGES);

  y = 18;
  y = sectionTitle(doc, 'Emissions Charts', M, y, 'Visual breakdown of your carbon footprint');
  y += 4;

  // --- Stacked rainbow bar (category split) ---
  y = sectionTitle(doc, 'Category Split', M, y, '');
  const catSorted = [...catData].sort((a, b) => b.value - a.value);
  const totalAll  = catSorted.reduce((s, c) => s + c.value, 0);

  if (totalAll > 0) {
    const STACK_H = 16;
    let sx = M;
    catSorted.forEach((cat) => {
      const segW = Math.max(0, (cat.value / totalAll) * CW);
      if (segW > 0) rr(doc, sx, y, segW, STACK_H, 0, CAT_META[cat.category]?.color ?? C.slate400);
      sx += segW;
    });
    // Rounded cap on start + end
    rr(doc, M,          y, 4, STACK_H, 2, CAT_META[catSorted[0]?.category]?.color ?? C.slate400);
    rr(doc, M + CW - 4, y, 4, STACK_H, 2, CAT_META[catSorted[catSorted.length - 1]?.category]?.color ?? C.slate400);
    y += STACK_H + 5;

    // Legend
    let lx = M;
    let legendY = y;
    catSorted.forEach((cat) => {
      const meta  = CAT_META[cat.category] ?? CAT_META.other;
      const pct   = ((cat.value / totalAll) * 100).toFixed(0);
      const label = `${meta.label} ${pct}%`;
      const tw    = doc.getTextWidth(label) + 10;

      if (lx + tw > W - M) { lx = M; legendY += 7; }

      rr(doc, lx, legendY, 5, 5, 1.5, meta.color);
      doc.setFontSize(7);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(C.slate600 ?? C.slate500);
      doc.text(label, lx + 7, legendY + 4);
      lx += tw + 3;
    });
    y = legendY + 10;
  } else {
    doc.setFontSize(9);
    doc.setTextColor(C.slate400);
    doc.text('No category data for this period.', M, y + 6);
    y += 14;
  }

  hLine(doc, M, y, CW);
  y += 8;

  // --- 7-day sparkline bars ---
  y = sectionTitle(doc, '7-Day Activity Trend', M, y, 'Daily total CO2e - last 7 days');
  y += 2;
  rr(doc, M, y, CW, 58, 3, C.slate100);
  drawWeeklyBars(doc, weeklyTrendData, M, y, CW, 58);
  y += 66;

  hLine(doc, M, y, CW);
  y += 8;

  // --- Monthly summary mini-table ---
  y = sectionTitle(doc, 'vs Monthly Target (150 kg CO2e)', M, y, '');
  y += 2;
  const monthRows = [
    { label: 'This period total', value: fmtKg(totalNow),    good: totalNow < 150 },
    { label: 'Monthly target',    value: '150 kg CO2e',       good: true  },
    {
      label: 'Difference',
      value: totalNow < 150
        ? `${(150 - totalNow).toFixed(1)} kg under target`
        : `${(totalNow - 150).toFixed(1)} kg over target`,
      good: totalNow < 150,
    },
  ];
  monthRows.forEach((row, i) => {
    rr(doc, M, y, CW, 9, 2, i % 2 === 0 ? C.slate100 : C.white);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate700);
    doc.text(row.label, M + 4, y + 6.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(row.good ? C.green : C.red);
    doc.text(row.value, M + CW - 4, y + 6.5, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    y += 9;
  });

  /* ═══════════════════════════════════════
     PAGE 4 — TOP ACTIVITIES TABLE
     ═══════════════════════════════════════ */
  doc.addPage();
  pageHeader(doc, W);
  pageFooter(doc, W, H, 4, PAGES);

  y = 18;
  y = sectionTitle(doc, 'Top Activities', M, y, 'Highest single-entry emissions this period');
  y += 3;

  // Table header
  rr(doc, M, y, CW, 9, 0, C.slate900);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.white);
  doc.text('#',       M + 3,      y + 6);
  doc.text('Activity', M + 13,    y + 6);
  doc.text('Category', M + 115,   y + 6);
  doc.text('CO2e',     M + CW - 3, y + 6, { align: 'right' });
  y += 9;

  if (!topActivities || topActivities.length === 0) {
    rr(doc, M, y, CW, 12, 2, C.slate100);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate400);
    doc.text('No activities logged in this period.', W / 2, y + 8, { align: 'center' });
    y += 14;
  } else {
    topActivities.slice(0, 22).forEach((act, i) => {
      if (y > H - 30) return;
      rr(doc, M, y, CW, 8, 0, i % 2 === 0 ? C.slate100 : C.white);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(C.slate700);
      doc.text(String(act.rank ?? i + 1), M + 3, y + 5.5);
      doc.text(
        (act.label ?? act.activityType ?? '--').substring(0, 40),
        M + 13, y + 5.5,
      );
      const catMeta = CAT_META[act.category] ?? CAT_META.other;
      doc.text(catMeta.label, M + 115, y + 5.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(C.red);
      doc.text(
        fmtKg(act.emissions ?? act.calculatedEmissions),
        M + CW - 3, y + 5.5, { align: 'right' },
      );
      doc.setTextColor(C.slate700);
      doc.setFont('helvetica', 'normal');
      y += 8;
    });
  }

  // Summary below table
  y += 6;
  hLine(doc, M, y, CW);
  y += 8;
  rr(doc, M, y, CW, 18, 3, C.greenLight);
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.green);
  doc.text('Period Summary', M + 6, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(C.slate700);
  doc.text(
    `${entries} activities logged  |  Total: ${fmtKg(totalNow)}  |  Avg: ${fmtKg(avgPerEntry)} per activity`,
    M + 6, y + 14,
  );

  /* ═══════════════════════════════════════
     PAGE 5 — TIPS & SIGN-OFF
     ═══════════════════════════════════════ */
  doc.addPage();
  pageHeader(doc, W);
  pageFooter(doc, W, H, 5, PAGES);

  y = 14;

  // Score banner
  rr(doc, M, y, CW, 22, 3, rating.color);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(C.white);
  doc.text(
    `Eco Score: ${ecoScore ?? '--'} / 850  -  ${rating.label}`,
    W / 2, y + 13.5, { align: 'center' },
  );
  y += 28;

  y = sectionTitle(
    doc,
    'Personalised Eco Tips',
    M, y,
    'Based on your activity patterns and eco score tier',
  );
  y += 3;

  getTipsForScore(ecoScore ?? 500).forEach((tip, i) => {
    if (y > H - 34) return;
    rr(doc, M, y, CW, 16, 2.5, i % 2 === 0 ? C.greenBg : C.white);
    // Bullet dot
    rr(doc, M + 4, y + 6, 4, 4, 2, C.green);
    doc.setFontSize(8.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate700);
    const lines = doc.splitTextToSize(tip, CW - 16);
    doc.text(lines.slice(0, 2), M + 12, y + 9);
    y += 18;
  });

  // Sign-off card
  y += 5;
  if (y < H - 50) {
    rr(doc, M, y, CW, 34, 4, C.greenLight);
    // Top green stripe
    rr(doc, M, y, CW, 10, 4, C.green);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(C.white);
    doc.text('Every action counts!', W / 2, y + 7, { align: 'center' });
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(C.slate700);
    doc.text('Keep logging your activities to improve your Eco Score', W / 2, y + 20, { align: 'center' });
    doc.text('and track your sustainability journey over time.', W / 2, y + 27, { align: 'center' });
  }

  /* ── Save ─────────────────────────────────────────────────── */
  const fileName = `CarbonTrack-Report-${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}.pdf`;
  doc.save(fileName);
  return fileName;
}

/* ── Tips per tier — ASCII only ──────────────────────────────── */
function getTipsForScore(score) {
  if (score >= 751) return [
    'Outstanding! You are in the top 8% of eco-conscious users on CarbonTrack.',
    'Challenge yourself: try a full zero-emission commute day this week.',
    'Share your green habits with friends to inspire your community.',
    'Consider solar panels or a green energy tariff to offset residual electricity.',
    'Explore certified carbon offset programmes (e.g. Gold Standard) for unavoidable emissions.',
  ];
  if (score >= 671) return [
    'Swap 2 meat meals for plant-based dishes this week to reach the Excellent tier.',
    'Unplug phantom devices (TVs, chargers on standby) to cut household energy by ~10%.',
    'Try carpooling or cycling at least twice a week to lower transport emissions.',
    'Opt for second-hand purchases or bulk buys to reduce shopping footprint.',
    'Log activities every day to build your consistency streak and boost your score.',
  ];
  if (score >= 551) return [
    'Use public transport twice a week - this alone can boost your score by +40 points.',
    'Log activities daily - consistency is the single biggest driver of a higher Eco Score.',
    'Switch all light bulbs to LED to cut lighting electricity use by up to 75%.',
    'Introduce one meat-free day per week to meaningfully reduce food emissions.',
    'Charge devices during off-peak hours to take advantage of lower-carbon grid periods.',
  ];
  return [
    'A high transport footprint was detected. Try carpooling or cycling where possible.',
    'Switch to energy-efficient LED bulbs throughout your home to lower electricity usage.',
    'Start small: introduce one plant-based meal per week and build from there.',
    'Log at least one activity per day to improve your consistency streak score.',
    'Unplug chargers and appliances when not in use - standby power adds up over a month.',
  ];
}
